inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 30
 
Naming/VariableNumber:
  Enabled: false 

