inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/AsciiComments:
  Enabled: false